#!/usr/bin/env python3
"""
Export TD3 PolyMixer coefficients to cpp/filament_mixer.h.

This script updates only the TD3 auto-generated block:
  // BEGIN AUTO-GENERATED TD3 COEFFICIENTS
  ...
  // END AUTO-GENERATED TD3 COEFFICIENTS
"""

from pathlib import Path
import sys


BEGIN = "// BEGIN AUTO-GENERATED TD3 COEFFICIENTS"
END = "// END AUTO-GENERATED TD3 COEFFICIENTS"


def build_td3_block() -> str:
    root = Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(root / "src"))

    from filament_mixer.poly_mixer import _BETA  # noqa: WPS433

    if _BETA.shape != (120, 3):
        raise ValueError(f"Unexpected _BETA shape {_BETA.shape}, expected (120, 3)")

    rows = "\n".join(
        f"    {{{r[0]:.17e}, {r[1]:.17e}, {r[2]:.17e}}}," for r in _BETA
    )

    lines = [
        "// Auto-generated by scripts/export_poly_td3_coefficients.py",
        "// Do not edit manually.",
        "// Total degree-3 hypercubic fit, 120 features, 7 inputs",
        "",
        "static const int TD3_FEATURES = 120;",
        "static const int TD3_INPUTS = 7;",
        "",
        "static const double BETA[TD3_FEATURES][3] = {",
        rows,
        "};",
    ]
    return "\n".join(lines)


def main():
    header_path = Path("cpp/filament_mixer.h")
    header = header_path.read_text()

    if BEGIN not in header or END not in header:
        raise RuntimeError(f"Could not find TD3 marker block in {header_path}")

    before = header[: header.index(BEGIN) + len(BEGIN)]
    after = header[header.index(END) :]
    updated = before + "\n" + build_td3_block() + "\n" + after
    header_path.write_text(updated)
    print(f"Updated {header_path}")


if __name__ == "__main__":
    main()
